### PR TITLE
Process privilege artifacts prior to access artifacts

### LINKED ISSUE #81: [Parsers] All the Privileges to be processed prior Access artifacts
```
2021-02-24 14:00:33.867 [ERROR] [pool-8-thread-1] o.e.d.c.s.api.AbstractSynchronizer - Resource [...] skipped due to an error: com.sap.xsk.xsaccess.ds.api.XSKAccessException: com.sap.xsk.xsaccess.ds.api.XSKPrivilegeException: No XSK Privilege found with name: {sap.sports.imp.api.downloadQueue::fetch}
org.eclipse.dirigible.core.scheduler.api.SynchronizationException: com.sap.xsk.xsaccess.ds.api.XSKAccessException: com.sap.xsk.xsaccess.ds.api.XSKPrivilegeException: No XSK Privilege found with name: {a.b.c.downloadQueue::fetch}
	at com.sap.xsk.xsaccess.ds.synchronizer.XSKSecuritySynchronizer.synchronizeAccess(XSKSecuritySynchronizer.java:256) ~[xsk-modules-engines-core-0.2.0-SNAPSHOT.jar:na]
	at com.sap.xsk.xsaccess.ds.synchronizer.XSKSecuritySynchronizer.synchronizeResource(XSKSecuritySynchronizer.java:295) ~[xsk-modules-engines-core-0.2.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:109) ~[dirigible-core-scheduler-5.8.1.jar:na]
```

### PR DESCRIPTION
**Pull request by d-velev**
closes #81

### CODE REVIEW

**Comment by d-velev** [comment]
@ThuF @delchev I wasn't too sure on how to name the sets and the method, is process the right word?

**Review by dpanayotov — CHANGES_REQUESTED** [review]
Can you please prove a simple test with 1 `.xsprivileges` and 1 `.xsaccess` file?
I'm still getting
```
KAccessException: com.sap.xsk.xsaccess.ds.api.XSKPrivilegeException: No XSK Privilege found with name: {privileges-test.folder1::Admin}
org.eclipse.dirigible.core.scheduler.api.SynchronizationException: com.sap.xsk.xsaccess.ds.api.XSKAccessException: com.sap.xsk.xsaccess.ds.api.XSKPrivilegeException: No XSK Privilege found with name: {privileges-test.folder1::Admin}
	at com.sap.xsk.xsaccess.ds.synchronizer.XSKSecuritySynchronizer.synchronizeAccess(XSKSecuritySynchronizer.java:244) ~[xsk-modules-engines-xssecurity-0.11.0-SNAPSHOT.jar:na]
	at com.sap.xsk.xsaccess.ds.synchronizer.XSKSecuritySynchronizer.synchronizeResource(XSKSecuritySynchronizer.java:283) ~[xsk-modules-engines-xssecurity-0.11.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:106) ~[dirigible-core-scheduler-6.1.3.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:113) ~[dirigible-core-scheduler-6.1.3.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:113) ~[dirigible-core-scheduler-6.1.3.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeRegistry(AbstractSynchronizer.java:90) ~[dirigible-core-scheduler-6.1.3.jar:na]
	at com.sap.xsk.xsaccess.ds.synchronizer.XSKSecuritySynchronizer.synchronizeRegistry(XSKSecuritySynchronizer.java:256) ~[xsk-modules-engines-xssecurity-0.11.0-SNAPSHOT.jar:na]
	at com.sap.xsk.xsaccess.ds.synchronizer.XSKSecuritySynchronizer.synchronize(XSKSecuritySynchronizer.java:88) ~[xsk-modules-engines-xssecurity-0.11.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:52) ~[dirigible-core-scheduler-6.1.3.jar:na]
	at org.eclipse.dirigible.commons.timeout.TimeLimited$1.call(TimeLimited.java:38) ~[dirigible-commons-timeout-6.1.3.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.sap.xsk.xsaccess.ds.api.XSKAccessException: com.sap.xsk.xsaccess.ds.api.XSKPrivilegeException: No XSK Privilege found with name: {privileges-test.folder1::Admin}
	at com.sap.xsk.xsaccess.ds.service.XSKAccessCoreService.createXSKAccessDefinition(XSKAccessCoreService.java:79) ~[xsk-modules-engines-xssecurity-0.11.0-SNAPSHOT.jar:na]
	at com.sap.xsk.xsaccess.ds.synchronizer.XSKSecuritySynchronizer.synchronizeAccess(XSKSecuritySynchronizer.java:225) ~[xsk-modules-engines-xssecurity-0.11.0-SNAPSHOT.jar:na]
	... 13 common frames omitted
Caused by: com.sap.xsk.xsaccess.ds.api.XSKPrivilegeException: No XSK Privilege found with name: {privileges-test.folder1::Admin}
	at com.sap.xsk.xsaccess.ds.service.XSKAccessCoreService.validatePrivileges(XSKAccessCoreService.java:210) ~[xsk-modules-engines-xssecurity-0.11.0-SNAPSHOT.jar:na]
	at com.sap.xsk.xsaccess.ds.service.XSKAccessCoreService.createXSKAccessDefinition(XSKAccessCoreService.java:61) ~[xsk-modules-engines-xssecurity-0.11.0-SNAPSHOT.jar:na]
	... 14 common frames omitted
```

I assume that's because on line 233 to the list only the name is added which later while being checked in `com.sap.xsk.xsaccess.ds.service.XSKAccessCoreService#validatePrivileges` is not found because the list has `Admin` but the authorization in `.xsaccess` is `privileges-test.folder1::Admin`

**Comment by d-velev** [comment]
@dpanayotov Could you provide the files you've tested with? I've tried with these and it works for me:
```javascript
{
  "exposed" : true,               // Expose data via http
  "authentication" :
         {
            "method": "Form"
         },
  "authorization":                // Privileges for application access
       ["Developer", "Administrator"]
}
```

```javascript
{
     "privileges" : [
         { "name" : "Developer", "description" : "Developer tasks execution privilege" },
         { "name" : "Administrator", "description" : "Administration privilege" }
     ]
}
```

**Comment by ThuF** [comment]
@d-velev shouldn't the Privileges and Access Maps be cleaned at the `cleanUp()` step?

**Comment by d-velev** [comment]
> @d-velev shouldn't the Privileges and Access Maps be cleaned at the `cleanUp()` step?

Which ones exactly?

**Review by ThuF — APPROVED** [review]
+1

**Pull request merged**
