### PR TITLE
Fix #765, add xsaccess editor

### LINKED ISSUE #765: [IDE] No option to create a .xsaccess file
Currently, there's no option to create a .`xsaccess` file through right click --> New--> filetype. None of the options available through this menu creates a `.xsaccess` file.

Screenshot 2021-11-11 at 9 55 45

**Expected behavior**
Such option should be available.

### PR DESCRIPTION
**Pull request by dimitarquanterall**
Signed-off-by: dimitarquanterall <d.aleksandrov@sap.com>

Closes sap/fundamental#

Fix #765

### CODE REVIEW

**Review by StanZGenchev — APPROVED** [review]

**Review by ThuF — APPROVED** [review]

**Comment by ThuF** [comment]
@dimitarquanterall could you please rebate the PR, as it seems the Sonar action failed to execute and the PR can’t be merged as, the Sonar action is required.

**Comment by dimitarquanterall** [comment]
The reason is lack of privileges: 
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project xsk-parent: **You're not authorized to run analysis**. No sonar.login or SONAR_TOKEN env variable was set -> [Help 1]

**Comment by vmutafov** [comment]
Should this PR be merged or it should be https://github.com/SAP/xsk/pull/1543 ? Please, do not leave multiple open PRs for the same feature/fix

**Comment by dimitarquanterall** [comment]
Duplicate PR

**Pull request closed without merging**
